//模拟MRPk控制在维护
export const MRPInfo = [
    {
        ID:"1",
        WerksID:"1",
        WerksName:"工厂01",
        TypeID:"1",
        TypeName:"业务01",
        MRP:"char10"
    },
    {
        ID:"2",
        WerksID:"2",
        WerksName:"工厂02",
        TypeID:"2",
        TypeName:"业务02",
        MRP:"CHAR10"
    },
    {
        ID:"3",
        WerksID:"2",
        WerksName:"工厂02",
        TypeID:"2",
        TypeName:"业务02",
        MRP:"CHAR10"
    },
    {
        ID:"4",
        WerksID:"1",
        WerksName:"工厂01",
        TypeID:"1",
        TypeName:"业务01",
        MRP:"CHAR10"
    }
]
//模拟工厂表数据
export const Werks =[
    {
        ID:"1",
        Code:"",
        Name:"工厂01"
    },
    {
        ID:"2",
        Code:"",
        Name:"工厂02"
    },
]
//模拟业务数据
export const TypeInfo = [
    {
        ID:"1",
        Name:"业务01"
    },
    {
        ID:"2",
        Name:"业务02"
    }
]
//模拟物料班组对照表
export const WBInfo =[
    {
        ID:"1",
        TypeID:"1",
        TypeName:"业务01",
        Matnr:'物料编码01',
        Maktx:'物料名称01',
        Group:'班组01'
    },
    {
        ID:"2",
        TypeID:"2",
        TypeName:"业务02",
        Matnr:'物料编码02',
        Maktx:'物料名称02',
        Group:'班组02'
    },
    {
        ID:"3",
        TypeID:"1",
        TypeName:"业务01",
        Matnr:'物料编码03',
        Maktx:'物料名称03',
        Group:'班组03'
    },
    {
        ID:"4",
        TypeID:"2",
        TypeName:"业务02",
        Matnr:'物料编码04',
        Maktx:'物料名称04',
        Group:'班组04'
    }
]
//钣金
export const BjInfo = [
    {
        ID:"1",
        FirstCode:"一层编码01",
        FirstName:"一层名称01",
        Prooerty:'属性01',
        SecondCode:'二层编码01',
        SecondName:'二层名称02',
        ThirdCode:'三层编码01',
        ThirdName:'三层名称01',
        FourthCode:'四层编码01',
        FourthName:'四层名称01',
        FifthCode:'五层编码01',
        FifthName:'五层名称01',
        Menge:'1'
    },
    {
        ID:"2",
        FirstCode:"一层编码02",
        FirstName:"一层名称02",
        Prooerty:'属性02',
        SecondCode:'二层编码02',
        SecondName:'二层名称02',
        ThirdCode:'三层编码02',
        ThirdName:'三层名称02',
        FourthCode:'四层编码02',
        FourthName:'四层名称02',
        FifthCode:'五层编码02',
        FifthName:'五层名称02',
        Menge:'2'
    },
    {
        ID:"3",
        FirstCode:"一层编码03",
        FirstName:"一层名称03",
        Prooerty:'属性03',
        SecondCode:'二层编码03',
        SecondName:'二层名称02',
        ThirdCode:'三层编码03',
        ThirdName:'三层名称03',
        FourthCode:'四层编码03',
        FourthName:'四层名称03',
        FifthCode:'五层编码03',
        FifthName:'五层名称03',
        Menge:'3'
    },
    {
        ID:"4",
        FirstCode:"一层编码04",
        FirstName:"一层名称04",
        Prooerty:'属性04',
        SecondCode:'二层编码04',
        SecondName:'二层名称02',
        ThirdCode:'三层编码04',
        ThirdName:'三层名称04',
        FourthCode:'四层编码04',
        FourthName:'四层名称04',
        FifthCode:'五层编码04',
        FifthName:'五层名称04',
        Menge:'4'
    },
    {
        ID:"5",
        FirstCode:"一层编码05",
        FirstName:"一层名称05",
        Prooerty:'属性05',
        SecondCode:'二层编码05',
        SecondName:'二层名称02',
        ThirdCode:'三层编码05',
        ThirdName:'三层名称05',
        FourthCode:'四层编码05',
        FourthName:'四层名称05',
        FifthCode:'五层编码05',
        FifthName:'五层名称05',
        Menge:'5'
    },
    {
        ID:"6",
        FirstCode:"一层编码06",
        FirstName:"一层名称06",
        Prooerty:'属性06',
        SecondCode:'二层编码06',
        SecondName:'二层名称02',
        ThirdCode:'三层编码06',
        ThirdName:'三层名称06',
        FourthCode:'四层编码06',
        FourthName:'四层名称06',
        FifthCode:'五层编码06',
        FifthName:'五层名称06',
        Menge:'6'
    },
] 
//机加
export const JjInfo = [
    {
        ID:'1',
        Series:'系列01',
        Matnr:'子键物料号01',
        Maktx:'子键物料描述01',
        Menge:'1',
        Group:'班组01'
    },
    {
        ID:'2',
        Series:'系列02',
        Matnr:'子键物料号02',
        Maktx:'子键物料描述02',
        Menge:'2',
        Group:'班组02'
    },
    {
        ID:'3',
        Series:'系列03',
        Matnr:'子键物料号03',
        Maktx:'子键物料描述03',
        Menge:'3',
        Group:'班组03'
    },
    {
        ID:'4',
        Series:'系列04',
        Matnr:'子键物料号04',
        Maktx:'子键物料描述04',
        Menge:'4',
        Group:'班组04'
    },
    {
        ID:'5',
        Series:'系列05',
        Matnr:'子键物料号05',
        Maktx:'子键物料描述05',
        Menge:'5',
        Group:'班组05'
    },
    {
        ID:'6',
        Series:'系列06',
        Matnr:'子键物料号06',
        Maktx:'子键物料描述06',
        Menge:'6',
        Group:'班组06'
    },
    {
        ID:'7',
        Series:'系列07',
        Matnr:'子键物料号07',
        Maktx:'子键物料描述07',
        Menge:'7',
        Group:'班组07'
    }
]
//采购需求
export const CgInfo = [
    {
        ID:'1',
        Maktx:'物料编码01',
        Matnr:'物料描述01',
        Budat:'2020-10-21',
        MRP:'MRP控制者01',
        Meins:'单位01',
        Lifnr:'供应商代码01',
        Name1:'供应商名称01'
    },
    {
        ID:'2',
        Maktx:'物料编码02',
        Matnr:'物料描述02',
        Budat:'2020-10-21',
        MRP:'MRP控制者02',
        Meins:'单位02',
        Lifnr:'供应商代码02',
        Name1:'供应商名称02'
    },
    {
        ID:'3',
        Maktx:'物料编码03',
        Matnr:'物料描述03',
        Budat:'2020-10-21',
        MRP:'MRP控制者03',
        Meins:'单位03',
        Lifnr:'供应商代码03',
        Name1:'供应商名称03'
    },
    {
        ID:'4',
        Maktx:'物料编码04',
        Matnr:'物料描述04',
        Budat:'2020-10-21',
        MRP:'MRP控制者04',
        Meins:'单位04',
        Lifnr:'供应商代码04',
        Name1:'供应商名称04'
    },
    {
        ID:'5',
        Maktx:'物料编码05',
        Matnr:'物料描述05',
        Budat:'2020-10-21',
        MRP:'MRP控制者05',
        Meins:'单位05',
        Lifnr:'供应商代码05',
        Name1:'供应商名称05'
    },
    {
        ID:'6',
        Maktx:'物料编码06',
        Matnr:'物料描述06',
        Budat:'2020-10-21',
        MRP:'MRP控制者06',
        Meins:'单位06',
        Lifnr:'供应商代码06',
        Name1:'供应商名称06'
    },
    {
        ID:'7',
        Maktx:'物料编码07',
        Matnr:'物料描述07',
        Budat:'2020-10-21',
        MRP:'MRP控制者07',
        Meins:'单位07',
        Lifnr:'供应商代码07',
        Name1:'供应商名称07'
    },
    
]
//调度单
export const UploadInfo = [
    {
        ID:'1',
        FileName:'001excel.excel',
        Path:'upload/excel/001excel.excel',
        Budat:'2020-10-10 15:20:21'
    },
    {
        ID:'2',
        FileName:'002excel.excel',
        Path:'upload/excel/002excel.excel',
        Budat:'2020-10-10 15:20:21'
    },
    {
        ID:'3',
        FileName:'003excel.excel',
        Path:'upload/excel/003excel.excel',
        Budat:'2020-10-10 15:20:21'
    },
    {
        ID:'4',
        FileName:'004excel.excel',
        Path:'upload/excel/004excel.excel',
        Budat:'2020-10-10 15:20:21'
    },
    {
        ID:'5',
        FileName:'005excel.excel',
        Path:'upload/excel/005excel.excel',
        Budat:'2020-10-10 15:20:21'
    },
    {
        ID:'6',
        FileName:'006excel.excel',
        Path:'upload/excel/006excel.excel',
        Budat:'2020-10-10 15:20:21'
    },
    {
        ID:'7',
        FileName:'007excel.excel',
        Path:'upload/excel/007excel.excel',
        Budat:'2020-10-10 15:20:21'
    },

]
//调度单表 Verson 2
export const dt_DdOrder= [
    {
        "ID":1,
        "LTOrder":"LT20210311",
        "TbCount":"2021040101",
        "Faline":"南线",
        "UpTime":"2021-03-30",
        "status":1,
        "BjStatus":"已完成",
        "JjStatus":"已完成",
        "CgStatus":"已完成",
        "RecTime":"2021-03-30",
    },
    {
        "ID":2,
        "LTOrder":"LT20210312",
        "TbCount":"2021040101",
        "Faline":"北线",
        "UpTime":"2021-03-30",
        "status":1,
        "BjStatus":"执行中",
        "JjStatus":"执行中",
        "CgStatus":"执行中",
        "RecTime":"2021-03-30",
    },
    {
        "ID":3,
        "LTOrder":"LT20210316",
        "TbCount":"2021040101",
        "Faline":"南线",
        "UpTime":"2021-03-30",
        "status":2,
        "BjStatus":"未执行",
        "JjStatus":"未执行",
        "CgStatus":"未执行",
        "RecTime":"2021-03-30",
    },
    {
        "ID":4,
        "LTOrder":"LT20210304",
        "TbCount":"2021040101",
        "Faline":"北线",
        "UpTime":"2021-03-30",
        "status":2,
        "BjStatus":"执行超时",
        "JjStatus":"执行超时",
        "CgStatus":"执行超时",
        "RecTime":"2021-03-30",
    },
    {
        "ID":5,
        "LTOrder":"LT20210305 ",
        "TbCount":"2021040101",
        "Faline":"北线",
        "UpTime":"2021-03-30",
        "status":1,
        "BjStatus":"异常",
        "JjStatus":"异常",
        "CgStatus":"异常",
        "RecTime":"2021-03-30",
    },
]