//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace luntuo.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LTPCwebserviceSoap", Namespace="http://tempuri.org/")]
    public partial class LTPCwebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MySoapHeader mySoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback DddxqfjOperationCompleted;
        
        private System.Threading.SendOrPostCallback CgxufjOperationCompleted;
        
        private System.Threading.SendOrPostCallback BjxufjOperationCompleted;
        
        private System.Threading.SendOrPostCallback JjxufjOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkSapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LTPCwebservice() {
            this.Url = global::luntuo.Properties.Settings.Default.luntuo_WebReference_LTPCwebservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MySoapHeader MySoapHeaderValue {
            get {
                return this.mySoapHeaderValueField;
            }
            set {
                this.mySoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DddxqfjCompletedEventHandler DddxqfjCompleted;
        
        /// <remarks/>
        public event CgxufjCompletedEventHandler CgxufjCompleted;
        
        /// <remarks/>
        public event BjxufjCompletedEventHandler BjxufjCompleted;
        
        /// <remarks/>
        public event JjxufjCompletedEventHandler JjxufjCompleted;
        
        /// <remarks/>
        public event ChkSapCompletedEventHandler ChkSapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Dddxqfj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Dddxqfj(string strDate, int iDID, string strType) {
            object[] results = this.Invoke("Dddxqfj", new object[] {
                        strDate,
                        iDID,
                        strType});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DddxqfjAsync(string strDate, int iDID, string strType) {
            this.DddxqfjAsync(strDate, iDID, strType, null);
        }
        
        /// <remarks/>
        public void DddxqfjAsync(string strDate, int iDID, string strType, object userState) {
            if ((this.DddxqfjOperationCompleted == null)) {
                this.DddxqfjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDddxqfjOperationCompleted);
            }
            this.InvokeAsync("Dddxqfj", new object[] {
                        strDate,
                        iDID,
                        strType}, this.DddxqfjOperationCompleted, userState);
        }
        
        private void OnDddxqfjOperationCompleted(object arg) {
            if ((this.DddxqfjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DddxqfjCompleted(this, new DddxqfjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cgxufj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Cgxufj(string strDate, string strUserCode, int iDID) {
            object[] results = this.Invoke("Cgxufj", new object[] {
                        strDate,
                        strUserCode,
                        iDID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CgxufjAsync(string strDate, string strUserCode, int iDID) {
            this.CgxufjAsync(strDate, strUserCode, iDID, null);
        }
        
        /// <remarks/>
        public void CgxufjAsync(string strDate, string strUserCode, int iDID, object userState) {
            if ((this.CgxufjOperationCompleted == null)) {
                this.CgxufjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCgxufjOperationCompleted);
            }
            this.InvokeAsync("Cgxufj", new object[] {
                        strDate,
                        strUserCode,
                        iDID}, this.CgxufjOperationCompleted, userState);
        }
        
        private void OnCgxufjOperationCompleted(object arg) {
            if ((this.CgxufjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CgxufjCompleted(this, new CgxufjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Bjxufj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Bjxufj(string strUserCode, int iDID) {
            object[] results = this.Invoke("Bjxufj", new object[] {
                        strUserCode,
                        iDID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BjxufjAsync(string strUserCode, int iDID) {
            this.BjxufjAsync(strUserCode, iDID, null);
        }
        
        /// <remarks/>
        public void BjxufjAsync(string strUserCode, int iDID, object userState) {
            if ((this.BjxufjOperationCompleted == null)) {
                this.BjxufjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBjxufjOperationCompleted);
            }
            this.InvokeAsync("Bjxufj", new object[] {
                        strUserCode,
                        iDID}, this.BjxufjOperationCompleted, userState);
        }
        
        private void OnBjxufjOperationCompleted(object arg) {
            if ((this.BjxufjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BjxufjCompleted(this, new BjxufjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Jjxufj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Jjxufj(string strUserCode, int iDID) {
            object[] results = this.Invoke("Jjxufj", new object[] {
                        strUserCode,
                        iDID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void JjxufjAsync(string strUserCode, int iDID) {
            this.JjxufjAsync(strUserCode, iDID, null);
        }
        
        /// <remarks/>
        public void JjxufjAsync(string strUserCode, int iDID, object userState) {
            if ((this.JjxufjOperationCompleted == null)) {
                this.JjxufjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJjxufjOperationCompleted);
            }
            this.InvokeAsync("Jjxufj", new object[] {
                        strUserCode,
                        iDID}, this.JjxufjOperationCompleted, userState);
        }
        
        private void OnJjxufjOperationCompleted(object arg) {
            if ((this.JjxufjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JjxufjCompleted(this, new JjxufjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkSap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkSap(string strType, string strUserCode, int iDID) {
            object[] results = this.Invoke("ChkSap", new object[] {
                        strType,
                        strUserCode,
                        iDID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkSapAsync(string strType, string strUserCode, int iDID) {
            this.ChkSapAsync(strType, strUserCode, iDID, null);
        }
        
        /// <remarks/>
        public void ChkSapAsync(string strType, string strUserCode, int iDID, object userState) {
            if ((this.ChkSapOperationCompleted == null)) {
                this.ChkSapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkSapOperationCompleted);
            }
            this.InvokeAsync("ChkSap", new object[] {
                        strType,
                        strUserCode,
                        iDID}, this.ChkSapOperationCompleted, userState);
        }
        
        private void OnChkSapOperationCompleted(object arg) {
            if ((this.ChkSapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkSapCompleted(this, new ChkSapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class MySoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DddxqfjCompletedEventHandler(object sender, DddxqfjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DddxqfjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DddxqfjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CgxufjCompletedEventHandler(object sender, CgxufjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CgxufjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CgxufjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BjxufjCompletedEventHandler(object sender, BjxufjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BjxufjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BjxufjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void JjxufjCompletedEventHandler(object sender, JjxufjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JjxufjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JjxufjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkSapCompletedEventHandler(object sender, ChkSapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkSapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkSapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591